#!/usr/bin/env zsh
# Copyright (c) 2023 Sebastian Gniazdowski
#
# zsqb – zs…quote…braces
#

zsqb() {

# Run as script?
[[ $0 != zsqb ]]&&integer bescript=1

# Set options
builtin emulate -L zsh -o extendedglob -o noshortloops \
                        -o warncreateglobal -o typesetsilent \
                        -o nopromptsubst

# Set $0 with a new trik - use of %x prompt expansion
0=${${(M)${0::=${(%):-%x}}:#/*}:-$PWD/$0}

local -A Opts
builtin zparseopts -D -E -A Opts -- o l||return 7

local sep=' '
(($+Opts[-l]))&&sep=$'\n'

local q='{' qn='\\{'

REPLY=${(j: :)${@//$q/$qn}}

(($+Opts[-o]))&&print -r -- $REPLY

}
