#!/usr/bin/env zsh

util/zs::chkstr() {

# Run as script?
[[ $0 != */zs::chkstr ]]&&integer bescript=1

# Set options
builtin emulate -L zsh -o extendedglob -o noshortloops \
                        -o warncreateglobal -o typesetsilent \
                        -o nopromptsubst

# $0 support
0=${${(M)${0::=${(%):-%x}}:#/*}:-$PWD/$0}

# -v verbose
# -G no cd, absolute paths
local -A Opts
builtin zparseopts ${${(M)ZSH_VERSION:#(5.[8-9]|6.[0-9])}:+-F} -D -E -A Opts -- || return 7

# Support running without quoting of the argument var
builtin set -- ${@[@]:-""}

REPLY=
local qe

for qe; do
    local qc="\"{205}${qe:-(nullstr)}{135}\""
    [[ $qe == INVALIDSTR ]]&&zsmsg -h %B{208}Error:{135} invalid byte in: $qc…
    [[ $qe == EMPTYSTR ]]&&zsmsg -h %B{208}Error:{135} no data in: $qc…
    [[ $qe != PRINTSTR ]]&&zsmsg -h %B{208}Error:{135} no visible data in: $qc…
    [[ $qe == CTRLSTR ]]&&zsmsg -h %B{208}Error:{135} control-only data in: $qc…
done

# REPLY is used to mark that zsmsg has been run
return REPLY

}
