#!/usr/bin/env zsh

util/zs::get-txt() {

#
# Copyright (c) 2023 Sebastian Gniazdowski
#

# Set options
builtin emulate -L zsh -o extendedglob -o noshortloops \
                        -o warncreateglobal -o typesetsilent \
                        -o nopromptsubst

# Possibly fix $0 with a new trick – use of a %x prompt expansion
0=${${(M)${0::=${(%):-%x}}:#/*}:-$PWD/$0}

# Input/options
local -A Opts
builtin zparseopts ${${(M)ZSH_VERSION:#(5.[8-9]|6.[0-9])}:+-F} -D -E -A Opts -- -c || return 1

: ${ZSTXT:=$0:h:h/txt}
local IN=$1

if [[ ! -d $ZSTXT ]];then
    zsmsg {err}Error:{txt} alias dir not set ({data}\$ZSTXT{txt})
    return 1
fi

local -a qa=($ZSTXT/${IN}_*[^~](#qNnon.,@Y1))
(($#qa))&&util/zs::read-file "$qa[1]" subst
return $?

}
