#!/usr/bin/env zsh

#
# Copyright (c) 2023 Sebastian Gniazdowski
#

# Set options
builtin emulate -L zsh -o extendedglob -o noshortloops \
                        -o warncreateglobal -o typesetsilent

# Possibly fix $0 with a new trick – use of a %x prompt expansion
0=${${(M)${0::=${(%):-%x}}:#/*}:-$PWD/$0}

# Input/options
local -A Opts
builtin zparseopts -D -E -A Opts -- -c || return 1

: ${ZSTXT:=$0:h:h/txt}
local IN=$1

if [[ ! -d $ZSTXT ]];then
    zsmsg {err}Error:{txt} alias dir not set ({data}\$ZSTXT{txt})
    return 1
fi

util/zs::read-file $ZSTXT/${IN}_* normal
return $?
