#!/usr/bin/env zsh

util/zs::get-prj-dir() {

# Set options
builtin emulate -L zsh -o extendedglob -o noshortloops \
                        -o warncreateglobal -o typesetsilent \
                        -o nopromptsubst

# Possibly fix $0 with a new trick – use of a %x prompt expansion
0=${${(M)${0::=${(%):-%x}}:#/*}:-$PWD/$0}

util/zs::up-find-dir() {
    local w=$1
    reply=($PWD/(../)#$w(N.,@,/))
    reply=(${(@On)reply})
    # Fix path's ../,etc.
    REPLY=$reply[1]:a
    [[ -n $REPLY ]]
}

# Input/options
local PRJ FILEDIR
local -a qt=(.git TAGS tags CMakeLists.txt configure)

# Iterate over special files/dirs
for FILEDIR ($qt); do
    util/zs::up-find-dir $FILEDIR&&PRJ=$REPLY&&break
done

REPLY=$REPLY:h
if [[ $PRJ == WRONGSTR ]]; then
    zswarn -h didn\'t find any main poject dir \
                uptree, was looking for: %B{39}·${(j.%f%b, %B{39}·.)qt}
    return 1
fi
return 0

}
