#!/usr/bin/env zsh

# Set options
builtin emulate -L zsh -o extendedglob -o kshglob -o noshortloops \
                        -o warncreateglobal -o typesetsilent

# Possibly fix $0 with a new trick – use of a %x prompt expansion
0=${${(M)${0::=${(%):-%x}}:#/*}:-$PWD/$0}
: ${TIG_SUITE_DIR:=$0:h:h} ${Plugins[TIG_DIR]:=$0:h:h}

if [[ ! -d $TIG_SUITE_DIR || ! -f $0 || ! -r $0 ]];then
    tigmsg -h %U{204}Error:%f cannot find/read %B{204}$TINICK%f%b program \
        directory, wrong or empty {39}\$TIG_SUITE_DIR%f \
        \(set to: {41}${TIG_SUITE_DIR:-(NULL)}%f\)
    return 1
fi

return 0
